name: Detect & Update ObservePoint

on:
  push:
    branches:
      - main

jobs:
  update-selectors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node and Python
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer axios
          pip install requests

      - name: Run selector analysis and update ObservePoint
        run: |
          node scripts/compare-selectors.js
          python scripts/update_observepoint.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OP_API_KEY: ${{ secrets.OP_API_KEY }}
